export { default as Home } from "./Home"
export { default as Movies } from "./Movies"
export { default as Shows } from "./Shows"
export { default as Watchlist } from "./Watchlist"
export { default as MediaDetails } from "./MediaDetails"
export { default as Login } from "./Login"
export { default as Register } from "./Register"